<?php

/*
 * @copyright   2018 Mautic Contributors. All rights reserved
 * @author      Mautic
 *
 * @link        http://mautic.org
 *
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 */

namespace MauticPlugin\CustomObjectsBundle\Segment\Decorator;

use Doctrine\ORM\EntityManager;
use Mautic\LeadBundle\Helper\FormFieldHelper;
use Mautic\LeadBundle\Segment\ContactSegmentFilterCrate;
use Mautic\LeadBundle\Segment\ContactSegmentFilterOperator;
use Mautic\LeadBundle\Segment\Decorator\CustomMappedDecorator;
use Mautic\LeadBundle\Services\ContactSegmentFilterDictionary;

/**
 * Class CompanyDecorator.
 */
class CountryDecorator extends CustomMappedDecorator
{
    /**
     * @var null|array
     */
    private $countryChoices = null;

    /**
     * @param ContactSegmentFilterCrate $contactSegmentFilterCrate
     *
     * @return array|bool|float|string|null
     */
    public function CgetParameterValue(ContactSegmentFilterCrate $contactSegmentFilterCrate)
    {
        $countryCode = $this->getCountryChoices();
        $crate = $contactSegmentFilterCrate;

        return parent::getParameterValue($contactSegmentFilterCrate); // TODO: Change the autogenerated stub
    }

    /**
     * @param ContactSegmentFilterCrate $contactSegmentFilterCrate
     *
     * @return null|string
     */
    public function getField(ContactSegmentFilterCrate $contactSegmentFilterCrate)
    {
        return parent::getField($contactSegmentFilterCrate); // TODO: Change the autogenerated stub
    }

    public function getTable(ContactSegmentFilterCrate $contactSegmentFilterCrate)
    {
        return parent::getTable($contactSegmentFilterCrate); // TODO: Change the autogenerated stub
    }

    private function getCountryChoices() {
        if (is_null($this->countryChoices)) {
            $this->countryChoices = array_flip(FormFieldHelper::getCountryChoices());
        }

        return $this->countryChoices;
    }
}
